### ISSUE TITLE
[Discussion] Any development on this?

### ISSUE THREAD

**Issue by stickyburn** [zmkfirmware/zmk-studio-old#9]
I think a GUI tool could really improve the UX for ZMK users. Any plans or help needed to get this going?

Thanks!

**Comment by byrantech** [comment]
Hi! We are currently discussing the best way forwards for ZMK in the Discord server. Nothing definitive has been reached yet. If you want to check out what the current plans are, feel free to join!
ZMK Studio's main structure would be WebHID over a web app or website, with correspondingly allocated storage in the chip for on-the-fly config changes. Totally up for change, however. I'll leave it to Pete et al for more detailed plans and descriptions  :)

**Comment by stickyburn** [comment]
Sounds pretty sweet! Its my first time with ZMK but I sure can help with Typescript/React. See you in Discord 😄

**Comment by CB-42458** [comment]
I am planning on creating a GUI tool for my CS NEA. It would take the required information by the user to then create the files necessary for ZMK. The tool could then create a push and GitHub actions would create the firmware (or firmware's). This would only be for new shields and existing boards/shields on the ZMK repo though.
I planned on making it in python using kivy.

**Comment by byrantech** [comment]
@CB-42458 https://github.com/nickcoutsos/keymap-editor
nickcoutsos has already make something like this that's a web based editor with a bot that changes your repo based on your actions in the GUI.  You can take a look at #studio-development and #studio-ideas to get an idea of what ZMK Studio is attempting to do. It is much more than just getting a GUI on top of Github Actions based compiling. It will be something similar to VIA/VIAL, where there is live keymap updating and on-the-fly reconfigurations.
